export const defaultTemplateFields = {
  student_name: {
    x: 421.125,
    y: 355.0,
    align: "center" as const,
    fontSize: 40,
    font: "TimesRomanBoldItalic",
  },
  description: {
    x: 421.125,
    y: 332.0,
    align: "center" as const,
    fontSize: 17,
    font: "Helvetica",
    maxWidth: 540,
    minFontSize: 12,
    maxLines: 3,
    lineHeight: 20,
  },
  score_text: {
    x: 421.125,
    y: 248.0,
    align: "center" as const,
    fontSize: 13,
    font: "Helvetica",
    maxWidth: 190,
    minFontSize: 10,
  },
  date_text: {
    x: 630.0,
    y: 248.0,
    align: "center" as const,
    fontSize: 13,
    font: "Helvetica",
    maxWidth: 210,
    minFontSize: 10,
  },
  mode_text: {
    x: 212.0,
    y: 248.0,
    align: "center" as const,
    fontSize: 13,
    font: "Helvetica",
    maxWidth: 140,
    minFontSize: 10,
  },
  collaboration_label: {
    x: 421.125,
    y: 210.0,
    align: "center" as const,
    fontSize: 12,
    font: "Helvetica",
    maxWidth: 420,
    minFontSize: 10,
  },
  serial_number: {
    x: 175.0,
    y: 130.0,
    align: "center" as const,
    fontSize: 9,
    font: "Helvetica",
  },
  instructor_label: {
    x: 680.0,
    y: 132.0,
    align: "center" as const,
    fontSize: 11,
    font: "Helvetica",
  },
  instructor_value: {
    x: 680.0,
    y: 150.0,
    align: "center" as const,
    fontSize: 20,
    font: "TimesRomanItalic",
  },
  qr_code: {
    x: 178.0,
    y: 180.0,
    width: 82,
    height: 82,
  },
  logo_image: {
    x: 421.125,
    y: 150.0,
    width: 100,
    height: 90,
  },
  signature_image: {
    x: 680.0,
    y: 170.0,
    width: 140,
    height: 55,
  },
}
