export const defaultTemplateFields = {
  student_name: {
    x: 421.125,
    y: 332.0,
    align: "center" as const,
    fontSize: 40,
    font: "TimesRomanBoldItalic",
  },
  description: {
    x: 421.125,
    y: 305.0,
    align: "center" as const,
    fontSize: 17,
    font: "Helvetica",
    maxWidth: 540,
    minFontSize: 12,
    maxLines: 2,
    lineHeight: 20,
  },
  serial_number: {
    x: 253.0,
    y: 150.0,
    align: "center" as const,
    fontSize: 9,
    font: "Helvetica",
  },
  instructor_name: {
    x: 585.0,
    y: 150.0,
    align: "center" as const,
    fontSize: 20,
    font: "TimesRomanItalic",
  },
  qr_code: {
    x: 255.0,
    y: 200.0,
    width: 82,
    height: 82,
  },
  logo_image: {
    x: 421.125,
    y: 170.0,
    width: 90,
    height: 90,
  },
  signature_image: {
    x: 585.0,
    y: 170.0,
    width: 140,
    height: 55,
  },
  signature_text: {
    x: 585.0,
    y: 165.0,
    align: "center" as const,
    fontSize: 14,
    font: "TimesRomanItalic",
  },
}
